scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090'] 
  - job_name: 'app'
    scrape_interval: 5s
    static_configs:
      - targets: ['f1-team-service:4000'] 

