apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-db
spec:
  replicas: 4
  selector:
    matchLabels:
      app: f1-db
  template:
    metadata:
      labels:
        app: f1-db
    spec:
      containers:
      - name: mongodb
        image: jefandrade/data-f1
        ports:
        - containerPort: 27017
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 20
          periodSeconds: 15
