apiVersion: v1
kind: Service
metadata:
  name: 'f1-team-service'
spec:
  selector:
    app: f1-team
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30001
  type: NodePort